baseurl = "/"
title = "Gleb's Website"
languageCode = "en-us"
theme = "hello-friend-ng"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

enableGitInfo = true
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[author]
  name = "Gleb Skibitsky"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 -0700"

  # Metadata mostly used in document's head
  description = "The personal website of Gleb Skibitsky"
  keywords = "homepage, blog, development, programming, games, blockchain, gamedev, skibickij"
  images = [""]

  homeSubtitle = "Software Engineer // Game Developer"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/skibitsky/skibitsky.github.io/commit/source"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Gleb Skibitsky"
    subtitle = "Gleb's Website"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "/about"
        url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "Projects"
      #   name = "Projects"
      #   url = "/projects"
      [[languages.en.menu.main]]
        identifier = "/uses"
        name = "/uses"
        url = "/uses"
      # [[languages.en.menu.main]]
      #   identifier = "Resume"
      #   name = "Resume"
      #   url = "/resume-skibitsky.pdf"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/skibitsky"

  [[params.social]]
    name = "telegram"
    url = "https://t.me/s/skibitsky"

  [[params.social]]
    name = "merveilles"
    url = "https://merveilles.town/@gleb"

  [[params.social]]
    name = "github"
    url = "https://github.com/skibitsky"

  [[params.social]]
    name = "spotify"
    url = "https://open.spotify.com/user/213ossaw3zv5tairnnielggjq?si=Y68r0uATTbmVdYIFDYKJCg"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/skibitsky/"

[mediaTypes]
  [mediaTypes."text/plain"]
  suffixes = ["asc"]

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"